version: '3.8'

services:
  database_budjet-app:
    image: postgres:latest
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: Budgy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Budgy_development
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  web:
    image: docker.io/sounak3007/budgetapp:5
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - database_budjet-app

volumes:
  db_data: 
