# apiVersion: tekton.dev/v1beta1
# kind: Task
# metadata:
#   name: build-image
# spec:
#   steps:
#   - name: build-and-push
#     image: gcr.io/kaniko-project/executor:v1.6.0
#     resources: {}
#     script: |
#       /kaniko/executor --context $(workspaces.source.path) --dockerfile $(params.pathToDockerfile) --destination $(params.image)

# ---
# apiVersion: tekton.dev/v1beta1
# kind: Task
# metadata:
#   name: build-and-push-image
# spec:
#   params:
#     - name: pathToDockerfile
#       type: string
#     - name: imageName
#       type: string
#   steps:
#     - name: build
#       image: gcr.io/kaniko-project/executor:latest
#       env:
#         - name: DOCKER_CONFIG
#           value: /kaniko/.docker/
#       command: ["/kaniko/executor"]
#       args:
#         - "--dockerfile=$(params.pathToDockerfile)"
#         - "--context=/workspace/source"
#         - "--destination=$(params.imageName)"
#         - "--destination=$(params.imageName):latest"
#       volumeMounts:
#         - name: docker-config
#           mountPath: /kaniko/.docker/
#         # - name: context
#         #   mountPath: /workspace/source
#         - name: workspace
#           mountPath: /workspace/source
#     - name: push
#       image: gcr.io/kaniko-project/executor:v1.6.0
#       env:
#         - name: DOCKER_CONFIG
#           value: /kaniko/.docker/
#       command: ["/kaniko/executor"]
#       args:
#         - "--dockerfile=$(params.pathToDockerfile)"
#         - "--context=/workspace/source"
#         - "--destination=$(params.imageName)"
#         - "--destination=$(params.imageName):latest"
#       volumeMounts:
#         - name: docker-config
#           mountPath: /kaniko/.docker/
#         - name: workspace
#           mountPath: /workspace/source
#   volumes:
#     - name: docker-config
#       emptyDir: {}
#     - name: workspace
#       emptyDir: {}

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-image
spec:
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/Sounak3007/Budget-App.git
        - name: revision
          value: master
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          emptyDir: {}
    - name: build-image
      taskRef:
        name: buildah-build
      params:
        - name: IMAGE
          value: sounak3007/budgetapp:latest
        - name: DOCKERFILE
          value: /workspace/output/Dockerfile
      resources:
        inputs:
          - name: source
            type: git
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: master
      workspaces:
        - name: source
          workspace: output
    - name: push-image
      taskRef:
        name: buildah-push
      params:
        - name: IMAGE
          value: sounak3007/budgetapp:latest

