apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-deploy-pipeline-run
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  workspaces:
    - name: Sounak3007/Budget-App
      persistentVolumeClaim:
        claimName: mypvc
        
        # apiVersion: v1
        # kind: PersistentVolumeClaim
        # metadata:
        #   name: mypvc
        # spec:
        #   resources:
        #     requests:
        #       storage: <Size>
        #   volumeMode: Filesystem
        #   accessModes:
        #     - ReadWriteOnce
        

