# # 

# apiVersion: tekton.dev/v1beta1
# kind: PipelineRun
# metadata:
#   generateName: build-and-push
# spec:
#   pipelineRef:
#     name: build-and-push-pipeline
#   resources:
#     - name: source-repo
#       resourceRef:
#         name: source-repo
#     - name: docker-image
#       resourceRef:
#         name: docker-image

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
spec:
  workspaces:
    - name: git-source
      description: The git repo
  params:
    - name: gitUrl
      default: https://github.com/Sounak3007/Budget-App.git
    - name: gitRevision
      description: Git revision to check out
      default: master
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    # - name: pathToYamlFile
    #   description: The path to the yaml file to deploy within the git source
    - name: imageUrl
      description: Image name including repository
      default: docker.io/sounak3007/budgetapp
    - name: imageTag
      description: Image tag
      default: "latest"
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "https://github.com/Sounak3007/Budget-App.git"
        - name: revision
          value: "$(params.gitRevision)"
        - name: subdirectory
          value: "."
        - name: deleteExisting
          value: "true"
    - name: source-to-image
      taskRef:
        name: kaniko
      runAfter:
        - clone-repo
      workspaces:
        - name: git-source
          workspace: git-source
      params:
        - name: CONTEXT
          value: $(params.pathToContext)
        - name: IMAGE
          value: $(params.imageUrl):$(params.imageTag)
    # - name: deploy-to-cluster
    #   taskRef:
    #     name: deploy-using-kubectl
    #   workspaces:
    #     - name: git-source
    #       workspace: git-source
    #   params:
    #     - name: pathToYamlFile
    #       value: $(params.pathToYamlFile)
    #     - name: imageUrl
    #       value: $(params.imageUrl)
    #     - name: imageTag
    #       value: $(params.imageTag)
    #     - name: imageDigest
    #       value: $(tasks.source-to-image.results.IMAGE-DIGEST)